FROM python:3-alpine
ENV PYTHONUNBUFFERED 1
RUN apk update && apk add --no-cache build-base python-dev py-pip jpeg-dev zlib-dev libpq postgresql-dev freetype-dev
ENV LIBRARY_PATH=/lib:/usr/lib
RUN mkdir /code
WORKDIR /code
ADD backend/requirements.txt /code/
RUN pip install -r requirements.txt
ADD ./backend /code/