# Generated by Django 2.1.5 on 2019-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_code', models.TextField(default='', verbose_name='Код карты (HTML)')),
                ('contacts_code', models.TextField(default='', verbose_name='Код контактных данных (HTML)')),
            ],
            options={
                'verbose_name': 'Контаты',
                'verbose_name_plural': 'Контаты',
            },
        ),
    ]
