# Generated by Django 2.1.5 on 2019-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190205_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(default=1000, help_text='Чем выше вес, тем выше элемент в списке ингредиентов.', verbose_name='Вес'),
        ),
    ]
