# Generated by Django 2.1.5 on 2019-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_ingredient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
