# Generated by Django 2.1.5 on 2019-02-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190212_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_hot',
            new_name='is_spicy',
        ),
    ]
