# Generated by Django 2.1.5 on 2019-02-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190217_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Для блока "С этим продуктом часто покупают"', to='shop.Product', verbose_name='Связанные продукты'),
        ),
    ]
