# Generated by Django 2.1.5 on 2019-02-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_related_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deliveryMode', models.CharField(choices=[('self', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=255, verbose_name='Способ доставки')),
                ('payMode', models.CharField(choices=[('cash', 'Наличными')], max_length=255, verbose_name='Метод оплаты')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента')),
                ('userphone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон клиента')),
                ('useraddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('usercomment', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Создан'), (2, 'Передан в службу доставки'), (3, 'Выдан')], verbose_name='Статус заказа')),
                ('cart', models.ManyToManyField(to='shop.CartProduct', verbose_name='Корзина')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
