# Generated by Django 2.1.5 on 2019-02-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cartproduct_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryMode',
            new_name='delivery_mode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payMode',
            new_name='pay_mode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='useraddress',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='usercomment',
            new_name='user_comment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userphone',
            new_name='user_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, to='shop.CartProduct', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Создан'), (2, 'Передан в службу доставки'), (3, 'Выдан')], default=1, verbose_name='Статус заказа'),
        ),
    ]
