# Generated by Django 2.1.5 on 2019-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190228_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail клиента'),
        ),
    ]
