# Generated by Django 2.1.5 on 2019-03-07 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190301_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frontpad_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Id в системе Frontpad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
