# Generated by Django 2.1.5 on 2019-03-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_deliverysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysettings',
            name='product',
        ),
        migrations.DeleteModel(
            name='DeliverySettings',
        ),
    ]
