# Generated by Django 2.1.5 on 2019-03-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20190314_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_mode',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Онлайн-оплата (Robokassa)')], max_length=255, verbose_name='Метод оплаты'),
        ),
    ]
