# Generated by Django 2.1.5 on 2019-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20190320_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='frontpad_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Артикул в системе Frontpad'),
        ),
    ]
