# Generated by Django 2.1.5 on 2019-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20190320_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_mode',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Онлайн-оплата (Robokassa)'), ('card', 'Оплата картой')], max_length=255, verbose_name='Метод оплаты'),
        ),
    ]
