# Generated by Django 2.1.5 on 2019-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20190329_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=1000, help_text='Чем выше вес, тем выше элемент в списке продуктов.', verbose_name='Вес'),
        ),
    ]
