# Generated by Django 2.1.5 on 2019-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190329_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='weight',
            field=models.IntegerField(default=1000, help_text='Чем выше вес, тем выше элемент в списке маркеров.', verbose_name='Вес'),
        ),
    ]
