# Generated by Django 2.1.5 on 2019-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20190526_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='tags',
            field=models.CharField(default='', help_text='Необходимо для генерации Title и Description', max_length=255, verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
