# Generated by Django 2.1.5 on 2019-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_ingredient_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, default='', help_text='Отображается на странице категории продуктов или ингредиента', null=True, verbose_name='Описание короткое'),
        ),
    ]
