# Generated by Django 2.1.5 on 2019-06-28 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Отображается на странице продукта', null=True, verbose_name='Описание полное'),
        ),
    ]
