# Generated by Django 2.1.5 on 2019-05-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Данные страницы', 'verbose_name_plural': 'Данные страницы'},
        ),
    ]
