# Generated by Django 2.1.5 on 2019-03-12 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='HTML-код')),
            ],
            options={
                'verbose_name': 'Контакты в "футере"',
                'verbose_name_plural': 'Контакты в "футере"',
            },
        ),
    ]
