# Generated by Django 2.1.5 on 2019-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_deliverysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255, verbose_name='Номер карты')),
            ],
            options={
                'verbose_name': 'Оплата картой',
                'verbose_name_plural': 'Оплата картой',
            },
        ),
    ]
