# Generated by Django 2.1.5 on 2019-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20190329_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое robots.txt')),
            ],
            options={
                'verbose_name': 'Содержимое robots.txt',
                'verbose_name_plural': 'Содержимое robots.txt',
            },
        ),
    ]
