# Generated by Django 2.1.5 on 2019-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_robotstxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotstxt',
            name='content',
            field=models.TextField(default='', verbose_name='Содержимое robots.txt'),
        ),
    ]
