# Generated by Django 2.1.5 on 2019-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20190525_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_title', models.CharField(max_length=255, verbose_name='Название социальной сети')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.CharField(max_length=255, verbose_name='HTML-код иконки')),
                ('weight', models.IntegerField(default=1000, help_text='Чем выше вес, тем левее элемент в списке ссылок на соц. сети.', verbose_name='Вес')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Ссылка на социальную сеть',
                'verbose_name_plural': 'Ссылки на социальные сети',
            },
        ),
    ]
