# Generated by Django 2.1.5 on 2019-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20190525_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Номер телефона в шапке',
                'verbose_name_plural': 'Номер телефона в шапке',
            },
        ),
    ]
