# Generated by Django 2.1.5 on 2019-05-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_headerphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerphone',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='Значение'),
        ),
    ]
