# Generated by Django 2.1.5 on 2019-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20190525_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код аналитики')),
            ],
            options={
                'verbose_name': 'HTML-код аналитики',
                'verbose_name_plural': 'HTML-код аналитики',
            },
        ),
    ]
