# Generated by Django 2.1.5 on 2019-06-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='code',
            field=models.TextField(default='', verbose_name='Код аналитики'),
        ),
    ]
