# Generated by Django 2.1.5 on 2019-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20190621_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Значение')),
                ('is_phone_number', models.BooleanField(default=True, help_text='Если это номер телефона, то на сайте будет отображён как ссылка.', verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт в шапке',
                'verbose_name_plural': 'Контакты в шапке',
            },
        ),
        migrations.DeleteModel(
            name='HeaderPhone',
        ),
    ]
