# Generated by Django 2.1.5 on 2019-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20190701_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpayment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплата'},
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='card_payment',
            field=models.BooleanField(default=True, verbose_name='Оплата картой'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='cash_payment',
            field=models.BooleanField(default=True, verbose_name='Оплата наличными'),
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='robokassa_payment',
            field=models.BooleanField(default=True, verbose_name='Оплата с помощью Robokassa'),
        ),
    ]
